tags:
  - name: Users
    description: users API

paths:
  # [login] user
  /login:
    post:
      tags:
        - Login
      summary: Login as user
      parameters:
        - name: body
          in: body
          description: user Data
          required: true
          schema:
            $ref: '#/definitions/users'
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] users
  /users:
    get:
      tags:
        - Users
      summary: Find All Users
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    # [POST] users
    post:
      tags:
        - Users
      summary: Add User
      parameters:
        - name: body
          in: body
          description: user Data
          required: true
          schema:
            $ref: '#/definitions/users'
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # users/id
  /users/{id}:
    # [GET] users/id
    get:
      tags:
        - Users
      summary: Find User By Id
      parameters:
        - name: id
          in: path
          description: User Id
          required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [PUT] users/id
    put:
      tags:
        - Users
      summary: Update User By Id
      parameters:
        - name: id
          in: path
          description: user Id
          required: true
        - name: body
          in: body
          description: user Data
          required: true
          schema:
            $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [DELETE] users/id
    delete:
      tags:
        - Users
      summary: Delete User By Id
      parameters:
        - name: id
          in: path
          description: user Id
          required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # tenants
  /tenants:
    # [POST] tenants
    post:
      tags:
        - Tenants
      summary: Add Tenant
      parameters:
        - name: body
          in: body
          description: Tenant Data
          required: true
          schema:
            $ref: '#/definitions/tenants'
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/tenants'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
    # [GET] tenants
    get:
      tags:
        - Tenants
      summary: Get All Tenants
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'


definitions:
  tenants:
    type: object
    required:
      - name
      - email
    properties:
      email:
        type: string
        description: tenant email
      lease_to:
        type: string
        format: date
        description: lease to
      move_in:
        type: string
        format: date
        description: move in
      name:
        type: string
        description: name
      phone:
        type: array
        items:
          type: string
        description: phone
      property:
        type: string
        description: property
      unit:
        type: string
        description: unit
      rentalAmount:
        type: number
        description: rental amount
      rentalBalance:
        type: number
        description: rentalBalance
  users:
    type: object
    required:
      - email
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password

schemes:
  - https
  - http

