import { config } from 'dotenv';

config({ path: `.env.${process.env.NODE_ENV || 'development'}.local` });

export const CREDENTIALS = process.env.CREDENTIALS === 'same-origin';
const {
  APP_ID,
  APP_SECRET,
  AWS_BUCKET,
  AWS_REGION,
  BUCKET_NAME,
  CLIENT_EMAIL,
  DB_DATABASE,
  DB_MEMORY,
  LOG_DIR,
  LOG_FORMAT,
  MONGO_URI,
  NODE_ENV,
  ORIGIN,
  PORT,
  PRIVATE_KEY,
  REDIRECT_URI,
  ROOT_URI,
  SECRET_KEY,
  STRIPE_ACCESS_KEY,
  STRIPE_PUBLISHABLE_KEY,
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
} = process.env;

export {
  APP_ID,
  APP_SECRET,
  AWS_BUCKET,
  AWS_REGION,
  BUCKET_NAME,
  CLIENT_EMAIL,
  DB_DATABASE,
  DB_MEMORY,
  LOG_DIR,
  LOG_FORMAT,
  MONGO_URI,
  NODE_ENV,
  ORIGIN,
  PORT,
  PRIVATE_KEY,
  REDIRECT_URI,
  ROOT_URI,
  SECRET_KEY,
  STRIPE_ACCESS_KEY,
  STRIPE_PUBLISHABLE_KEY,
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
};
