name: Update Version
on:
#  push:
#    branches: [ main ]
  pull_request:
    branches: [ main ]
    types:
      - closed
  workflow_dispatch:
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "19.x"
      - name: Install dependencies
        run: npm ci
      - name: Create new release
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
